name: azure-sklearn1.3-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
    - pandas==1.5.3
    - numpy==1.23.5
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - azureml-defaults==1.53.0
    - inference-schema[numpy-support]==1.5.1
    - joblib==1.2.0